[build]
functions = "functions"
publish = "build"

[[redirects]]
to = "/.netlify/functions/:splat"
from = "/api/*"
status = 200

[[headers]]
for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"